title: Morgan's blog
email: morgan.sadr@gmail.com
description: >-
  Development Team Lead at Nested. I like tech, gym and food.
baseurl: ""
url: "https://sadir.github.io/"
twitter_username: sadir_
github_username:  sadir

locale: "en-gb"
logo: "/images/sadir.png"
read_time: true
search_full_content: true
date_format: "%d-%m-%Y"
footer_links:
  - title: Twitter
    url: https://twitter.com/sadir_
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/sadir
    icon: fab fa-github-square
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square
copyright: "Hand crafted and totally not just Github pages."

paginate: 10
paginate_path: /page:num/

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

markdown: kramdown
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed
  - jekyll-archives
