title: Morgan's blog
email: morgan.sadr@gmail.com
description: >-
  Development Team Lead at Nested. I like tech, gym and food.
baseurl: ""
url: "https://sadir.github.io/"

locale: "en-gb"
logo: "/images/sadir.png"

read_time: true

paginate: 10
paginate_path: /page:num/

search_full_content: true

date_format: "%d-%m-%Y"

twitter_username: sadir_
github_username:  sadir

markdown: kramdown
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed
