author: Morgan Sadr-Hashemi
title: Morgan's blog
description: >-
  Engineering Manager at Nested. I like tech, gym and food.
baseurl: "/personal-site"
url: "https://sadir.github.io"
author:
  twitter: sadir_
  picture: /images/morgan-medium.jpg

jekyll-archives:
  enabled: "all"
  layouts:
    category: archive
    day: day-archive
    month: month-archive
    tag: archive
    year: year-archive
  permalinks:
    category: '/archives/category/:name/'
    year: '/archives/year/:year/'
    month: '/archives/year/:year/month/:month/'
    day: '/archives/year/:year/month/:month/day/:day/'
    tag: '/archives/tag/:name/'

logo: "/images/morgan-medium.jpg"
menu:
  - href: "/about"
    text: About
  - href: "/cv"
    text: CV
  - href: "/posts"
    text: Posts
  - href: "/archives"
    text: Archives
  - href: "https://github.com/sadir/jekyll-sadir"
    text: Get this theme

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

paginate: 2
paginate_path: "/posts/:num/"

permalink: /:year/:month/:day/:title:output_ext

twitter_url: https://twitter.com/sadir_
linkedin_url: https://www.linkedin.com/in/morgan-sadr-hashemi/
github_url: https://github.com/sadir
rss_feed: true

markdown: kramdown

jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: public
  license: all-rights-reserved
  text: '<p><i>Feedback welcome on Medium or Twitter.</i></p>'
  backdate: true

remote_theme: "sadir/jekyll-sadir"

plugins:
  - jekyll-archives
  - jekyll-crosspost-to-medium
  - jekyll-feed
  - jekyll-octicons
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
